#!/usr/bin/env bash
set -e

PI_DIR="$HOME/.pi/agent"
SRC_DIR="$(cd "$(dirname "$0")" && pwd)"
INTERACTIVE=true
[[ "$1" == "--no-interactive" ]] && INTERACTIVE=false

echo "================================================"
echo "   Pi-Powerkit - One-Click Setup"
echo "   Configures Pi + OMP + Zed + Copilot + jcode"
echo "================================================"
echo ""

mkdir -p "$PI_DIR"/extensions "$PI_DIR"/cache

# Source .env
ENV_FILE="$SRC_DIR/.env"
[ -f "$ENV_FILE" ] && set -a && source "$ENV_FILE" && set +a && echo "  -> .env loaded"

# Prompt for API keys
echo ""
for var in AIHUBMIX_API_KEY ROUTER9_API_KEY XIAOMI_API_KEY DATABRICKS_API_KEY MODAL_API_KEY KILO_API_KEY AGENTROUTER_API_KEY; do
  VAL="${!var}"
  if [ -z "$VAL" ] && [ "$INTERACTIVE" = true ]; then
    read -rp "  Enter $var (or press Enter to skip): " VAL
    export "$var=$VAL"
  fi
done

# =========================================================
#  1. PI SETUP
# =========================================================
echo ""
echo "--- Pi ---"

# settings.json
if [ ! -f "$PI_DIR/settings.json" ]; then
  if [ -f "$SRC_DIR/bootstrap/settings.json" ]; then
    cp "$SRC_DIR/bootstrap/settings.json" "$PI_DIR/settings.json"
    echo "  settings.json created"
  fi
else
  echo "  settings.json exists (skipped)"
fi

# models.json
echo "  Generating models.json..."
TEMPLATE=$(cat "$SRC_DIR/bootstrap/models.json")
for var in AIHUBMIX_API_KEY ROUTER9_API_KEY XIAOMI_API_KEY DATABRICKS_API_KEY MODAL_API_KEY KILO_API_KEY AGENTROUTER_API_KEY; do
  VAL="${!var}"
  [ -z "$VAL" ] && VAL="YOUR_${var}"
  ESCAPED_VAL=$(printf '%s\n' "$VAL" | sed 's/[&/\]/\\&/g')
  TEMPLATE=$(echo "$TEMPLATE" | sed "s/\${$var}/$ESCAPED_VAL/g")
done
echo "$TEMPLATE" > "$PI_DIR/models.json"
echo "  models.json generated"

# Extensions
echo "  Copying extensions..."
for ext in pi-ddg-search pi-ssh; do
  SRC="$SRC_DIR/packages/$ext/extensions"
  [ -d "$SRC" ] && cp "$SRC"/*.ts "$PI_DIR/extensions/" 2>/dev/null && echo "  -> $ext copied"
done

# .env.example
if [ ! -f "$PI_DIR/.env" ] && [ -f "$SRC_DIR/bootstrap/.env.example" ]; then
  cp "$SRC_DIR/bootstrap/.env.example" "$PI_DIR/.env"
  echo "  .env example copied"
fi

# =========================================================
#  2. OMP SETUP (~/.omp/agent/models.yml)
# =========================================================
echo ""
echo "--- OMP (Oh My Pi) ---"
OMP_DIR="$HOME/.omp/agent"
if [ -d "$OMP_DIR" ]; then
  OMP_FILE="$OMP_DIR/models.yml"
  echo "# Custom providers (generated by Pi-Powerkit setup)" > "$OMP_FILE"
  echo "providers:" >> "$OMP_FILE"
  for name in router9 databricks agentrouter aihubmix; do
    KEY_VAR=$(echo "${name}_API_KEY" | tr '[:lower:]' '[:upper:]')
    KEY_VAL="${!KEY_VAR}"
    [ -z "$KEY_VAL" ] && KEY_VAL="YOUR_${KEY_VAR}"
    case "$name" in
      router9)
        echo "  router9:" >> "$OMP_FILE"
        echo "    baseUrl: https://api.router9.com/v1" >> "$OMP_FILE"
        echo "    apiKey: $KEY_VAL" >> "$OMP_FILE"
        echo "    auth: apiKey" >> "$OMP_FILE"
        echo "    api: openai-completions" >> "$OMP_FILE"
        echo "    models:" >> "$OMP_FILE"
        echo "      - id: minimax/minimax-m3" >> "$OMP_FILE"
        echo "        name: MiniMax M3 (via Router9)" >> "$OMP_FILE"
        echo "        reasoning: true" >> "$OMP_FILE"
        echo "        input: [text, image]" >> "$OMP_FILE"
        echo "        contextWindow: 1000000" >> "$OMP_FILE"
        echo "        maxTokens: 65536" >> "$OMP_FILE"
        ;;
      databricks)
        echo "  databricks:" >> "$OMP_FILE"
        echo "    baseUrl: https://dbc-3e029138-076b.cloud.databricks.com/ai-gateway/mlflow/v1" >> "$OMP_FILE"
        echo "    apiKey: $KEY_VAL" >> "$OMP_FILE"
        echo "    auth: apiKey" >> "$OMP_FILE"
        echo "    api: openai-completions" >> "$OMP_FILE"
        echo "    models:" >> "$OMP_FILE"
        echo "      - id: system.ai.glm-5-2" >> "$OMP_FILE"
        echo "        name: Databricks GLM-5-2" >> "$OMP_FILE"
        echo "        reasoning: false" >> "$OMP_FILE"
        echo "        input: [text]" >> "$OMP_FILE"
        echo "        contextWindow: 128000" >> "$OMP_FILE"
        echo "        maxTokens: 32768" >> "$OMP_FILE"
        ;;
      agentrouter)
        echo "  agentrouter:" >> "$OMP_FILE"
        echo "    baseUrl: https://agentrouter.org/v1" >> "$OMP_FILE"
        echo "    apiKey: $KEY_VAL" >> "$OMP_FILE"
        echo "    auth: apiKey" >> "$OMP_FILE"
        echo "    api: openai-completions" >> "$OMP_FILE"
        echo "    models:" >> "$OMP_FILE"
        echo "      - id: claude-opus-4-8" >> "$OMP_FILE"
        echo "        name: Claude Opus 4.8 (via AgentRouter)" >> "$OMP_FILE"
        echo "        reasoning: true" >> "$OMP_FILE"
        echo "        input: [text]" >> "$OMP_FILE"
        echo "        contextWindow: 1000000" >> "$OMP_FILE"
        echo "        maxTokens: 128000" >> "$OMP_FILE"
        ;;
      aihubmix)
        echo "  aihubmix:" >> "$OMP_FILE"
        echo "    baseUrl: https://aihubmix.com/v1" >> "$OMP_FILE"
        echo "    apiKey: $KEY_VAL" >> "$OMP_FILE"
        echo "    auth: apiKey" >> "$OMP_FILE"
        echo "    api: openai-completions" >> "$OMP_FILE"
        echo "    models:" >> "$OMP_FILE"
        echo "      - id: coding-glm-5.2-free" >> "$OMP_FILE"
        echo "        name: Coding GLM-5.2 Free" >> "$OMP_FILE"
        echo "        reasoning: true" >> "$OMP_FILE"
        echo "        input: [text]" >> "$OMP_FILE"
        echo "        contextWindow: 128000" >> "$OMP_FILE"
        echo "        maxTokens: 65536" >> "$OMP_FILE"
        ;;
    esac
    echo "" >> "$OMP_FILE"
  done
  echo "  models.yml generated ($OMP_FILE)"
else
  echo "  OMP not installed (no ~/.omp/agent dir) — skipped"
fi

# =========================================================
#  3. ZED SETUP (~/.config/zed/settings.json)
# =========================================================
echo ""
echo "--- Zed ---"
ZED_FILE="$HOME/.config/zed/settings.json"
if [ -f "$ZED_FILE" ]; then
  python3 << 'PYEOF' "$ZED_FILE"
import json, sys, os

f = sys.argv[1]
with open(f) as fp:
    d = json.load(fp)

# Create openai_compatible section if missing
if 'language_models' not in d:
    d['language_models'] = {'openai_compatible': {}}
if 'openai_compatible' not in d['language_models']:
    d['language_models']['openai_compatible'] = {}

oc = d['language_models']['openai_compatible']
oc.setdefault('aihubmix', {'api_url': 'https://aihubmix.com/v1', 'available_models': [
    {"name": "coding-glm-5.2-free", "display_name": "Coding GLM-5.2 (FREE)", "max_tokens": 128000, "max_output_tokens": 65536, "protocol": "openai_chat", "subscription": "free", "reasoning_effort_levels": ["low","medium","high"], "interleaved_reasoning": True},
    {"name": "coding-kimi-k3-free", "display_name": "Coding Kimi K3 (FREE)", "max_tokens": 128000, "max_output_tokens": 32768, "protocol": "openai_chat", "subscription": "free"},
    {"name": "gemini-3.6-flash-free", "display_name": "Gemini 3.6 Flash (FREE)", "max_tokens": 128000, "max_output_tokens": 32768, "protocol": "openai_chat", "subscription": "free"},
    {"name": "gemma-4-26b-a4b-it-free", "display_name": "Gemma 4 26B (FREE)", "max_tokens": 262144, "max_output_tokens": 32768, "protocol": "openai_chat", "subscription": "free"},
    {"name": "gpt-5.5-free", "display_name": "GPT-5.5 (FREE)", "max_tokens": 272000, "max_output_tokens": 65536, "protocol": "openai_chat", "subscription": "free"},
    {"name": "nemotron-3-nano-30b-a3b-free", "display_name": "Nemotron 3 Nano 30B (FREE)", "max_tokens": 128000, "max_output_tokens": 16384, "protocol": "openai_chat", "subscription": "free"},
    {"name": "xiaomi-mimo-v2.5-free", "display_name": "MiMo V2.5 (FREE)", "max_tokens": 1048576, "max_output_tokens": 131072, "protocol": "openai_chat", "subscription": "free"},
    {"name": "kimi-for-coding-free", "display_name": "Kimi for Coding (FREE)", "max_tokens": 128000, "max_output_tokens": 16384, "protocol": "openai_chat", "subscription": "free"}
]})
oc.setdefault('router9', {'api_url': 'https://api.router9.com/v1', 'available_models': [
    {"name": "minimax/minimax-m3", "display_name": "MiniMax M3 (Router9)", "max_tokens": 1000000, "max_output_tokens": 65536}
]})

with open(f, 'w') as fp:
    json.dump(d, fp, indent=2)
    fp.write('\n')

print("  aihubmix + router9 added to settings.json")
PYEOF
else
  echo "  Zed not installed (no settings.json) — skipped"
fi

# =========================================================
#  4. COPILOT SETUP (~/.config/Code/User/chatLanguageModels.json)
# =========================================================
echo ""
echo "--- VS Code Copilot ---"
COPILOT_FILE="$HOME/.config/Code/User/chatLanguageModels.json"
if [ -f "$COPILOT_FILE" ]; then
  python3 << 'PYEOF' "$COPILOT_FILE"
import json, sys

f = sys.argv[1]
with open(f) as fp:
    d = json.load(fp)

# Check if aihubmix already exists
if not any(e.get('name') == 'AIHubMix FREE' for e in d):
    d.append({
        "name": "AIHubMix FREE",
        "vendor": "customendpoint",
        "apiKey": "",
        "apiType": "chat-completions",
        "models": [
            {"id": "coding-glm-5.2-free", "name": "Coding GLM-5.2 (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "thinking": True, "supportsReasoningEffort": ["low","medium","high"], "maxInputTokens": 128000, "maxOutputTokens": 65536},
            {"id": "coding-kimi-k3-free", "name": "Coding Kimi K3 (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "maxInputTokens": 128000, "maxOutputTokens": 32768},
            {"id": "gemini-3.6-flash-free", "name": "Gemini 3.6 Flash (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "maxInputTokens": 128000, "maxOutputTokens": 32768},
            {"id": "gemma-4-26b-a4b-it-free", "name": "Gemma 4 26B (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "maxInputTokens": 262144, "maxOutputTokens": 32768},
            {"id": "gpt-5.5-free", "name": "GPT-5.5 (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "maxInputTokens": 272000, "maxOutputTokens": 65536},
            {"id": "kimi-for-coding-free", "name": "Kimi for Coding (FREE)", "url": "https://aihubmix.com/v1/chat/completions", "toolCalling": True, "maxInputTokens": 128000, "maxOutputTokens": 16384}
        ]
    })
    print("  AIHubMix FREE added to Copilot")
else:
    print("  AIHubMix already in Copilot (skipped)")

with open(f, 'w') as fp:
    json.dump(d, fp, indent=2)
    fp.write('\n')
PYEOF
else
  echo "  VS Code Copilot not installed (no chatLanguageModels.json) — skipped"
fi

# =========================================================
#  5. JCODE SETUP (jcode provider add)
# =========================================================
echo ""
echo "--- jcode ---"
if command -v jcode &>/dev/null; then
  AIHUBMIX_KEY="${AIHUBMIX_API_KEY:-}"
  if [ -n "$AIHUBMIX_KEY" ] && ! jcode provider list 2>/dev/null | grep -q aihubmix; then
    echo "$AIHUBMIX_KEY" | jcode provider add aihubmix \
      --base-url https://aihubmix.com/v1 \
      --model coding-glm-5.2-free \
      --api-key-stdin \
      --context-window 128000 \
      --no-update 2>/dev/null && echo "  aihubmix provider added to jcode" || echo "  jcode aihubmix skipped"
  else
    echo "  aihubmix already in jcode or no key (skipped)"
  fi
else
  echo "  jcode not installed — skipped"
fi

# =========================================================
#  6. INSTALL AGENT-BROWSER
# =========================================================
echo ""
echo "--- Browser ---"
if ! command -v agent-browser &>/dev/null; then
  echo "  Installing agent-browser..."
  npm install -g agent-browser 2>/dev/null || npm install agent-browser --prefix "$HOME/.local" 2>/dev/null || true
  echo "  agent-browser installed"
else
  echo "  agent-browser already installed"
fi

# =========================================================
#  DONE
# =========================================================
echo ""
echo "================================================"
echo "   Setup complete!"
echo "================================================"
echo ""
echo "  Configured:"
echo "    - Pi: 8 providers, 50+ models + search + SSH"
echo "    - OMP: custom providers (if installed)"
echo "    - Zed: aihubmix + router9 (if installed)"
echo "    - Copilot: AIHubMix FREE (if VS Code installed)"
echo "    - jcode: aihubmix provider (if jcode installed)"
echo ""
echo "  Next:"
echo "    1. Edit .env for missing API keys"
echo "    2. Restart pi (and other tools)"
echo ""
